on:
  release:
    types:
      - published
name: publish
env:
  CARGO_TERM_COLOR: always
jobs:
  publish:
    needs: [release-please]
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v1
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_REGISTRY_TOKEN}}
