on:
  push:
    branches:
      - main
name: release-please
permissions:
  contents: write
  pull-requests: write
env:
  CARGO_TERM_COLOR: always
jobs:
  release-please:
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: rust
          package-name: sysinfo-report
